name: "è€å¼ çš„ä¸å¹¸ç”Ÿæ´»"
author: "Zhang Kai"
highlighter: rouge
permalink: /:year/:month/:day/:title
paginate: 50
paginate_path: /blog/page:num/

navigations:
  - title: About
    icon: ğŸ‘¤
    href: /about.html
